name: Alto
on:
  pull_request:
  push:
    branches:
      - main
      - 'renovate/*'
    paths:
      - 'packages/alto/**'
      - '.github/workflows/alto.yml'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - run: pnpm test:ci --theme alto
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Deploy theme
        uses: TryGhost/action-deploy-theme@101a83f96f8e54826640a62e8ce47201f8b10d4b # v2
        with:
          api-url: ${{ secrets.ALTO_GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.ALTO_GHOST_ADMIN_API_KEY }}
          working-directory: packages/alto
  subtree:
    name: Subtree
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
      - uses: nxtlvlsoftware/git-subtree-action@3d555981a570a2275a91c07b04b38d5e90d48c05 # 1.1
        with:
          repo: 'TryGhost/Alto'
          path: 'packages/alto'
          deploy_key: ${{secrets.ALTO_GITHUB_DEPLOY_KEY}}
          force: true
